Repository Samsung/LPVS, pull requests merged in 2023-11, with the labels that each got.

#293 fix: Update test-suite.yml for displaying the code coverage in correct format
  .github/workflows/test-suite.yml
  README.md
Labels: github_actions

#296 fix: Remove unused frontend modules and fix incorrect UT on backend
  frontend/package-lock.json
  frontend/package.json
  src/main/java/com/lpvs/service/LPVSGitHubService.java
  src/main/java/com/lpvs/service/OAuthService.java
  src/test/java/com/lpvs/service/OAuthServiceTest.java
Labels: fix

#295 fix: Fix for "Security-Policy" warning about missing info in SECURITY.md
  .github/SECURITY.md
Labels: fix

#299 feat: Add more unit tests to improve coverage
  .github/workflows/test-suite.yml
  src/main/java/com/lpvs/service/LPVSLicenseService.java
  src/main/java/com/lpvs/service/LPVSStatisticsService.java
  src/main/java/com/lpvs/service/scanner/scanoss/LPVSScanossDetectService.java
  src/main/java/com/lpvs/util/LPVSCommentUtil.java
  src/main/java/com/lpvs/util/LPVSExitHandler.java
  src/main/java/com/lpvs/util/LPVSFileUtil.java
  src/test/java/com/lpvs/config/SecurityConfigTest.java
  src/test/java/com/lpvs/entity/LPVSFileTest.java
  src/test/java/com/lpvs/entity/LPVSPullRequestTest.java
  src/test/java/com/lpvs/entity/LPVSQueueTest.java
  src/test/java/com/lpvs/entity/LPVSResponseWrapperTest.java
  src/test/java/com/lpvs/service/LPVSGitHubServiceTest.java
  src/test/java/com/lpvs/service/LPVSLicenseServiceTest.java
  src/test/java/com/lpvs/service/LPVSLoginCheckServiceTest.java
  src/test/java/com/lpvs/service/LPVSQueueServiceTest.java
  src/test/java/com/lpvs/service/LPVSStatisticsServiceTest.java
  src/test/java/com/lpvs/service/scanner/scanoss/LPVSScanossDetectServiceTest.java
  src/test/java/com/lpvs/util/LPVSCommentUtilTest.java
  src/test/java/com/lpvs/util/LPVSExitHandlerTest.java
  src/test/java/com/lpvs/util/LPVSFileUtilTest.java
  src/test/java/com/lpvs/util/LPVSWebhookUtilTest.java
  src/test/resources/A_B.json
Labels: enhancement

#306 docs: Add link to the frontend readme inside the main readme
  .github/CODE_OF_CONDUCT.md
  README.md
Labels: documentation

#308 docs: Enable Javadoc generation as GitHub action
  .github/workflows/javadoc.yml
  doc/overview.html
  pom.xml
  src/main/java/com/lpvs/LicensePreValidationSystem.java
  src/main/java/com/lpvs/controller/GitHubWebhooksController.java
  src/main/java/com/lpvs/controller/LPVSWebController.java
  src/main/java/com/lpvs/controller/package-info.java
  src/main/java/com/lpvs/package-info.java
  src/test/java/com/lpvs/controller/GitHubWebhooksControllerTest.java
  src/test/java/com/lpvs/controller/LPVSWebControllerTest.java
Labels: documentation

#311 fix: Use actions-gh-pages for publication of Javadoc
  .github/workflows/javadoc.yml
Labels: github_actions, fix

#313 fix: Update github->action javadoc permissions
  .github/workflows/javadoc.yml
Labels: github_actions, fix

#315 docs: Add Javadoc comments for config, exception, repository and unit
  doc/overview.html
  src/main/java/com/lpvs/config/SecurityConfig.java
  src/main/java/com/lpvs/config/package-info.java
  src/main/java/com/lpvs/entity/result/LPVSResult.java
  src/main/java/com/lpvs/entity/result/LPVSResultFile.java
  src/main/java/com/lpvs/entity/result/LPVSResultInfo.java
  src/main/java/com/lpvs/exception/ErrorResponse.java
  src/main/java/com/lpvs/exception/LoginFailedException.java
  src/main/java/com/lpvs/exception/PageControllerAdvice.java
  src/main/java/com/lpvs/exception/WrongAccessException.java
  src/main/java/com/lpvs/exception/package-info.java
  src/main/java/com/lpvs/repository/LPVSDetectedLicenseRepository.java
  src/main/java/com/lpvs/repository/LPVSLicenseConflictRepository.java
  src/main/java/com/lpvs/repository/LPVSLicenseRepository.java
  src/main/java/com/lpvs/repository/LPVSMemberRepository.java
  src/main/java/com/lpvs/repository/LPVSPullRequestRepository.java
  src/main/java/com/lpvs/repository/LPVSQueueRepository.java
  src/main/java/com/lpvs/repository/package-info.java
  src/main/java/com/lpvs/util/LPVSCommentUtil.java
  src/main/java/com/lpvs/util/LPVSExitHandler.java
  src/main/java/com/lpvs/util/LPVSFileUtil.java
  src/main/java/com/lpvs/util/LPVSTableConfiguration.java
  src/main/java/com/lpvs/util/LPVSWebhookUtil.java
  src/main/java/com/lpvs/util/package-info.java
Labels: documentation

#322 fix: Provide reproducible builds
  pom.xml
Labels: fix

#326 fix: Specifies the version of the components used in the clusterfuzzlite
  .clusterfuzzlite/Dockerfile
  .github/workflows/cflite_batch.yml
Labels: gold

#325 fix: Apply hardening mechanisms to controller endpoints
  src/main/java/com/lpvs/LicensePreValidationSystem.java
  src/main/java/com/lpvs/controller/GitHubWebhooksController.java
  src/main/java/com/lpvs/controller/LPVSWebController.java
  src/main/java/com/lpvs/util/LPVSWebhookUtil.java
  src/test/java/com/lpvs/controller/LPVSWebControllerTest.java
  src/test/java/com/lpvs/util/LPVSWebhookUtilTest.java
Labels: java, gold

#328 docs: Update of YAML file with newly added endpoints
  .github/CONTRIBUTING.md
  doc/lpvs-api.yaml
  pom.xml
  src/main/java/com/lpvs/controller/GitHubWebhooksController.java
Labels: documentation

#330 docs: Update of the issue and PR templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/task.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation
