Repository Samsung/LPVS, pull requests merged in 2023-12, with the labels that each got.

#300 feat: Enable starting scans with pull request argument
  README.md
  pom.xml
  src/main/java/com/lpvs/entity/LPVSQueue.java
  src/main/java/com/lpvs/service/LPVSDetectService.java
  src/main/java/com/lpvs/service/LPVSGitHubConnectionService.java
  src/main/java/com/lpvs/service/LPVSGitHubService.java
  src/main/java/com/lpvs/service/LPVSQueueProcessorService.java
  src/main/java/com/lpvs/service/scanner/scanoss/LPVSScanossDetectService.java
  src/main/resources/application-singlescan.properties
  src/main/resources/data-h2.sql
  src/main/resources/schema-h2.sql
  src/test/java/com/lpvs/service/LPVSDetectServiceTest.java
  src/test/java/com/lpvs/service/LPVSGitHubServiceTest.java
  src/test/java/com/lpvs/service/LPVSLoginCheckServiceTest.java
  src/test/java/com/lpvs/service/scanner/scanoss/LPVSScanossDetectServiceTest.java
Labels: java, new feature

#355 docs: Update and extension of Javadocs for entities
  src/main/java/com/lpvs/controller/LPVSWebController.java
  src/main/java/com/lpvs/entity/LPVSDetectedLicense.java
  src/main/java/com/lpvs/entity/LPVSDiffFile.java
  src/main/java/com/lpvs/entity/LPVSFile.java
  src/main/java/com/lpvs/entity/LPVSLicense.java
  src/main/java/com/lpvs/entity/LPVSLicenseConflict.java
  src/main/java/com/lpvs/entity/LPVSPullRequest.java
  src/main/java/com/lpvs/entity/LPVSPullRequestFilesUrlResponse.java
  src/main/java/com/lpvs/entity/LPVSQueue.java
  src/main/java/com/lpvs/entity/LPVSResponseWrapper.java
  src/main/java/com/lpvs/entity/auth/LPVSLoginMember.java
  src/main/java/com/lpvs/entity/auth/LPVSMember.java
  src/main/java/com/lpvs/entity/auth/MemberProfile.java
  src/main/java/com/lpvs/entity/auth/package-info.java
  src/main/java/com/lpvs/entity/dashboard/DashBoardElements.java
  src/main/java/com/lpvs/entity/dashboard/Dashboard.java
  src/main/java/com/lpvs/entity/dashboard/DashboardElementsByDate.java
  src/main/java/com/lpvs/entity/dashboard/package-info.java
  src/main/java/com/lpvs/entity/enums/Grade.java
  src/main/java/com/lpvs/entity/enums/LPVSPullRequestAction.java
  src/main/java/com/lpvs/entity/enums/LPVSPullRequestStatus.java
  src/main/java/com/lpvs/entity/enums/LPVSVcs.java
  src/main/java/com/lpvs/entity/enums/OAuthAttributes.java
  src/main/java/com/lpvs/entity/enums/package-info.java
  src/main/java/com/lpvs/entity/history/HistoryEntity.java
  src/main/java/com/lpvs/entity/history/HistoryPageEntity.java
  src/main/java/com/lpvs/entity/history/LPVSHistory.java
  src/main/java/com/lpvs/entity/history/package-info.java
  src/main/java/com/lpvs/entity/package-info.java
  src/main/java/com/lpvs/entity/result/LPVSResult.java
  src/main/java/com/lpvs/entity/result/LPVSResultFile.java
  src/main/java/com/lpvs/entity/result/LPVSResultInfo.java
  src/main/java/com/lpvs/entity/result/package-info.java
  src/main/java/com/lpvs/repository/LPVSMemberRepository.java
  src/main/java/com/lpvs/repository/package-info.java
  src/main/java/com/lpvs/service/LPVSLoginCheckService.java
  src/main/java/com/lpvs/service/LPVSStatisticsService.java
  src/main/java/com/lpvs/service/OAuthService.java
  src/main/java/com/lpvs/util/package-info.java
  src/test/java/com/lpvs/controller/LPVSWebControllerTest.java
  src/test/java/com/lpvs/entity/LPVSLoginMemberTest.java
  src/test/java/com/lpvs/entity/LPVSMemberTest.java
  src/test/java/com/lpvs/entity/LPVSPullRequestFilesUrlResponseTest.java
  src/test/java/com/lpvs/entity/auth/MemberProfileTest.java
  src/test/java/com/lpvs/service/LPVSLoginCheckServiceTest.java
  src/test/java/com/lpvs/service/LPVSStatisticsServiceTest.java
Labels: documentation

#356 test: Update ClusterFuzzLite github->action
  .clusterfuzzlite/build.sh
  .github/workflows/cflite_batch.yml
  src/test/java/com/lpvs/entity/LPVSFileTestFuzzer.java
  src/test/java/com/lpvs/util/LPVSWebhookUtilTestFuzzer.java
Labels: github_actions

#357 fix: Apply security install of python package into Dockerfile
  Dockerfile
Labels: bug, docker, fix

#360 docs: Add Javadoc comments for services
  src/main/java/com/lpvs/service/LPVSDetectService.java
  src/main/java/com/lpvs/service/LPVSGitHubConnectionService.java
  src/main/java/com/lpvs/service/LPVSGitHubService.java
  src/main/java/com/lpvs/service/LPVSLicenseService.java
  src/main/java/com/lpvs/service/LPVSLoginCheckService.java
  src/main/java/com/lpvs/service/LPVSQueueProcessorService.java
  src/main/java/com/lpvs/service/LPVSQueueService.java
  src/main/java/com/lpvs/service/LPVSStatisticsService.java
  src/main/java/com/lpvs/service/OAuthService.java
  src/main/java/com/lpvs/service/package-info.java
  src/main/java/com/lpvs/service/scanner/scanoss/LPVSScanossDetectService.java
  src/main/java/com/lpvs/service/scanner/scanoss/package-info.java
Labels: documentation

#358 feat: Generate html report for single scan mode
  README.md
  src/main/java/com/lpvs/service/LPVSDetectService.java
  src/main/java/com/lpvs/util/LPVSCommentUtil.java
  src/test/java/com/lpvs/service/LPVSDetectServiceTest.java
  src/test/java/com/lpvs/util/LPVSCommentUtilTest.java
Labels: new feature

#363 fix: Fix existing javadoc comments
  src/main/java/com/lpvs/entity/auth/LPVSMember.java
  src/main/java/com/lpvs/service/LPVSDetectService.java
  src/main/java/com/lpvs/util/LPVSCommentUtil.java
Labels: documentation, fix

#364 feat: Adding automatic release generation
  .github/workflows/create-release.yml
Labels: github_actions

#366 fix: Fix Dockerfile for secure installation of scanoss package
  Dockerfile
Labels: bug, fix

#368 docs: Updated links in Readme file
  README.md
Labels: documentation
