Repository Samsung/LPVS, pull requests merged in 2024-09, with the labels that each got.

#580 fix: Warning messages removal during the build process
  src/main/java/com/lpvs/config/SecurityConfig.java
  src/main/java/com/lpvs/entity/report/LPVSReportBuilder.java
  src/test/java/com/lpvs/LicensePreValidationServiceTest.java
  src/test/java/com/lpvs/service/OAuthServiceTest.java
Labels: fix

#593 build: Update python requirements
  requirements.txt
Labels: dependencies

#594 docs: Prepared API reference, Integration guide, Webhook configuration and Docker run pages
  doc/docs/dev-guide/api.md
  doc/docs/dev-guide/integration.md
  doc/docs/img/webhook/step_1_1.png
  doc/docs/img/webhook/step_1_2.png
  doc/docs/img/webhook/step_1_3.png
  doc/docs/img/webhook/step_1_4.png
  doc/docs/user-guide/README.md
  doc/docs/user-guide/service/docker.md
  doc/docs/user-guide/service/webhook.md
  doc/mkdocs.yml
Labels: documentation

#596 fix: Add missing property to remove run errors
  src/main/resources/application-singlescan.properties
Labels: fix

#597 docs: Prepared Prerequisites, Command line mode and Configuration pages
  doc/docs/css/mkdocsoad.css
  doc/docs/dev-guide/integration.md
  doc/docs/user-guide/README.md
  doc/docs/user-guide/cli/cli_file.md
  doc/docs/user-guide/cli/cli_pr.md
  doc/docs/user-guide/config/database.md
  doc/docs/user-guide/config/options.md
  doc/docs/user-guide/service/build-and-run.md
  doc/docs/user-guide/service/database.md
  doc/docs/user-guide/service/scanner.md
  doc/mkdocs.yml
  doc/quick-start-guide-and-build.md
Labels: documentation

#599 refactor: Separate queue service and implement factory for webhooks
  src/main/java/com/lpvs/entity/report/package-info.java
  src/main/java/com/lpvs/service/LPVSQueueProcessorService.java
  src/main/java/com/lpvs/service/LPVSQueueService.java
  src/main/java/com/lpvs/service/webhook/LPVSWebhookService.java
  src/main/java/com/lpvs/service/webhook/LPVSWebhookServiceFactory.java
  src/main/java/com/lpvs/service/webhook/LPVSWebhookServiceImpl.java
  src/main/java/com/lpvs/service/webhook/package-info.java
  src/test/java/com/lpvs/service/LPVSQueueProcessorServiceTest.java
  src/test/java/com/lpvs/service/LPVSQueueServiceTest.java
  src/test/java/com/lpvs/service/webhook/LPVSWebhookServiceFactoryTest.java
  src/test/java/com/lpvs/service/webhook/LPVSWebhookServiceImplTest.java
Labels: documentation, enhancement

#598 ci: update documentation management job with MkDocs
  .github/workflows/publish-documentation.yml
  .github/workflows/publish-release.yml
Labels: github_actions

#602 docs: Add quick start guide
  README.md
  doc/docs/dev-guide/README.md
  doc/docs/dev-guide/integration.md
  doc/docs/dev-guide/testing-policy.md
  doc/docs/img/result.png
  doc/docs/quick-start-guide.md
  doc/docs/user-guide/service/webhook.md
  doc/mkdocs.yml
  docker-compose-quick.yml
Labels: documentation

#606 fix: Update README.md
  README.md
Labels: documentation, fix

#604 ci: Fix issue with not pinned dependancies for docs generation
  .github/workflows/publish-documentation.yml
  doc/requirements-docs.txt
Labels: github_actions

#605 feat: Add default endpoint that forward POST requests to /webhooks
  doc/docs/user-guide/service/database.md
  doc/docs/user-guide/service/webhook.md
  doc/lpvs-api.yaml
  src/main/java/com/lpvs/controller/GitHubController.java
  src/test/java/com/lpvs/controller/GitHubControllerTest.java
Labels: documentation, enhancement

#609 fix: Update Security guide
  .github/SECURITY.md
Labels: documentation

#612 docs: Add information of performance monitoring tools
  doc/docs/user-guide/README.md
  doc/docs/user-guide/performance.md
  doc/mkdocs.yml
Labels: documentation

#613 fix: Update the clusterfuzzlite docker container
  .clusterfuzzlite/Dockerfile
Labels: bug

#614 chore: Change version to 2.0.0 for release
  pom.xml
Labels: release

#615 refactor: improve MCD (Module Circular Dependency) metric of the code
  src/main/java/com/lpvs/entity/LPVSConflict.java
  src/main/java/com/lpvs/entity/report/LPVSReportBuilder.java
  src/main/java/com/lpvs/service/LPVSGitHubService.java
  src/main/java/com/lpvs/service/LPVSLicenseService.java
  src/main/java/com/lpvs/service/scan/LPVSDetectService.java
  src/main/java/com/lpvs/service/webhook/LPVSWebhookServiceImpl.java
  src/test/java/com/lpvs/entity/LPVSConflictTest.java
  src/test/java/com/lpvs/entity/report/LPVSReportBuilderTest.java
  src/test/java/com/lpvs/service/LPVSGitHubServiceTest.java
  src/test/java/com/lpvs/service/LPVSLicenseServiceTest.java
  src/test/java/com/lpvs/service/scan/LPVSDetectServiceTest.java
Labels: enhancement

#616 feat: Display link to the hub in pull request message when available
  src/main/java/com/lpvs/service/LPVSGitHubService.java
  src/test/java/com/lpvs/service/LPVSGitHubServiceTest.java
Labels: enhancement

#617 refactor: Add queue ID to the PR diffs filepath
  src/main/java/com/lpvs/entity/LPVSPullRequest.java
  src/main/java/com/lpvs/repository/LPVSPullRequestRepository.java
  src/main/java/com/lpvs/service/webhook/LPVSWebhookServiceImpl.java
  src/main/java/com/lpvs/util/LPVSFileUtil.java
  src/main/resources/database_dump.sql
  src/test/java/com/lpvs/entity/LPVSPullRequestTest.java
  src/test/java/com/lpvs/entity/history/HistoryPageEntityTest.java
  src/test/java/com/lpvs/service/scan/scanner/LPVSScanossDetectServiceTest.java
  src/test/java/com/lpvs/util/LPVSFileUtilTest.java
  src/test/java/com/lpvs/util/LPVSPayloadUtilTest.java
  src/test/resources/1-A_B.json
Labels: enhancement

#618 fix: Change query to database to avoid the runtime error
  src/main/java/com/lpvs/repository/LPVSPullRequestRepository.java
Labels: fix

#619 fix: Incorrect conversion to string when equals to null
  src/main/java/com/lpvs/util/LPVSFileUtil.java
Labels: fix

#620 docs: Update FAQ page with generation Python requirements guide
  doc/docs/dev-guide/faq.md
  doc/mkdocs.yml
Labels: documentation
