Repository Samsung/LPVS, pull requests merged in 2024-03, with the labels that each got.

#447 fix: Remove unnecessary try/catch section from the service
  src/main/java/com/lpvs/repository/LPVSLicenseRepository.java
  src/main/java/com/lpvs/service/LPVSGitHubService.java
  src/main/java/com/lpvs/service/LPVSQueueService.java
  src/test/java/com/lpvs/service/LPVSGitHubServiceTest.java
  src/test/java/com/lpvs/service/LPVSQueueServiceTest.java
Labels: fix

#463 fix: modify single scan feature
  src/main/java/com/lpvs/entity/LPVSDetectedLicense.java
  src/main/java/com/lpvs/entity/LPVSLicense.java
  src/main/java/com/lpvs/entity/LPVSLicenseConflict.java
  src/main/java/com/lpvs/entity/LPVSPullRequest.java
  src/main/java/com/lpvs/entity/LPVSQueue.java
  src/main/java/com/lpvs/entity/auth/LPVSMember.java
  src/main/java/com/lpvs/service/LPVSDetectService.java
  src/main/java/com/lpvs/service/LPVSLicenseService.java
  src/main/resources/application-singlescan.properties
  src/main/resources/application.properties
  src/test/java/com/lpvs/service/LPVSDetectServiceTest.java
  src/test/java/com/lpvs/service/LPVSLicenseServiceTest.java
Labels: fix

#449 chore: change version to 1.4.2
  docker-compose.yml
  pom.xml
Labels: release

#464 fix: Fix Javadoc generation
  .github/workflows/publish-release.yml
  pom.xml
  src/main/java/com/lpvs/controller/LPVSWebController.java
  src/main/java/com/lpvs/service/LPVSStatisticsService.java
Labels: dependencies, fix

#465 fix: Fix issues detected by Svace code analyzer
  src/main/java/com/lpvs/controller/GitHubController.java
  src/main/java/com/lpvs/service/LPVSGitHubService.java
  src/main/java/com/lpvs/service/LPVSStatisticsService.java
  src/main/java/com/lpvs/service/scanner/scanoss/LPVSScanossDetectService.java
  src/main/java/com/lpvs/util/LPVSCommentUtil.java
Labels: fix

#470 feat: Load scan services dynamically based on configuration properties
  src/main/java/com/lpvs/service/LPVSQueueService.java
  src/main/java/com/lpvs/service/scan/LPVSDetectService.java
  src/main/java/com/lpvs/service/scan/LPVSScanService.java
  src/main/java/com/lpvs/service/scan/LPVSScanServiceFactory.java
  src/main/java/com/lpvs/service/scan/package-info.java
  src/main/java/com/lpvs/service/scan/scanner/LPVSScanossDetectService.java
  src/main/java/com/lpvs/service/scan/scanner/package-info.java
  src/test/java/com/lpvs/service/LPVSQueueServiceTest.java
  src/test/java/com/lpvs/service/scan/LPVSDetectServiceTest.java
  src/test/java/com/lpvs/service/scan/LPVSScanServiceFactoryTest.java
  src/test/java/com/lpvs/service/scan/scanner/LPVSScanossDetectServiceTest.java
Labels: new feature
