Repository Samsung/LPVS, pull requests merged in 2024-05, with the labels that each got.

#516 build: Remove hardcoded dependencies from POM file
  .clusterfuzzlite/Dockerfile
  pom.xml
Labels: enhancement

#517 chore: Fix a typo in the quick-start-guide regarding the launch of th…
  doc/quick-start-guide-and-build.md
Labels: fix

#514 feat: Check new license and alternative license names in OSORI DB
  src/main/java/com/lpvs/service/LPVSLicenseService.java
  src/main/java/com/lpvs/service/LPVSQueueService.java
  src/main/java/com/lpvs/service/scan/scanner/LPVSScanossDetectService.java
  src/main/java/com/lpvs/util/LPVSPayloadUtil.java
  src/main/resources/application.properties
  src/test/java/com/lpvs/service/LPVSGitHubServiceTest.java
  src/test/java/com/lpvs/service/LPVSLicenseServiceTest.java
  src/test/java/com/lpvs/service/LPVSQueueServiceTest.java
  src/test/java/com/lpvs/service/scan/scanner/LPVSScanossDetectServiceTest.java
  src/test/java/com/lpvs/util/LPVSPayloadUtilTest.java
  src/test/resources/osori_db_response1.json
  src/test/resources/osori_db_response2.json
Labels: new feature

#518 fix: Fix svace issue Redundant null check
  src/main/java/com/lpvs/service/LPVSGitHubService.java
  src/main/java/com/lpvs/service/LPVSLicenseService.java
  src/main/java/com/lpvs/service/LPVSQueueService.java
  src/test/java/com/lpvs/service/LPVSGitHubServiceTest.java
  src/test/java/com/lpvs/service/LPVSQueueServiceTest.java
Labels: fix

#519 fix: Fix logs and exceptions handling for single scan mode
  src/main/java/com/lpvs/LicensePreValidationService.java
  src/main/java/com/lpvs/service/LPVSGitHubService.java
  src/main/java/com/lpvs/service/scan/LPVSDetectService.java
  src/main/java/com/lpvs/service/scan/scanner/LPVSScanossDetectService.java
  src/test/java/com/lpvs/service/scan/LPVSDetectServiceTest.java
  src/test/java/com/lpvs/service/scan/scanner/LPVSScanossDetectServiceTest.java
  src/test/java/com/lpvs/util/LPVSCommentUtilTest.java
Labels: fix

#523 refactor: Refactor LoginCheck and existing unit test for License Service
  src/main/java/com/lpvs/controller/LPVSWebController.java
  src/main/java/com/lpvs/service/LPVSLoginCheckService.java
  src/test/java/com/lpvs/controller/GitHubControllerTest.java
  src/test/java/com/lpvs/service/LPVSLicenseServiceTest.java
Labels: enhancement
