Repository Samsung/LPVS, pull requests merged in 2024-02, with the labels that each got.

#408 ci: Test java-kotlin for codeql analysis
  .github/workflows/codeql.yml
Labels: github_actions

#420 refactor: Sync source code with external modules
  pom.xml
  src/main/java/com/lpvs/entity/LPVSDetectedLicense.java
  src/main/java/com/lpvs/entity/LPVSLicense.java
  src/main/java/com/lpvs/entity/LPVSLicenseConflict.java
  src/main/java/com/lpvs/entity/LPVSPullRequest.java
  src/main/java/com/lpvs/entity/LPVSQueue.java
  src/main/java/com/lpvs/entity/auth/LPVSMember.java
  src/main/java/com/lpvs/entity/enums/LPVSPullRequestAction.java
  src/main/java/com/lpvs/service/LPVSGitHubService.java
  src/main/java/com/lpvs/util/LPVSFileUtil.java
  src/main/resources/application.properties
  src/test/java/com/lpvs/entity/enums/LPVSPullRequestActionTest.java
  src/test/java/com/lpvs/service/LPVSGitHubServiceTest.java
  src/test/java/com/lpvs/util/LPVSFileUtilTest.java
Labels: enhancement

#421 chore: Update package version to 1.4.1
  pom.xml
Labels: release

#422 fix: Fix package-lock dependencies
  frontend/package-lock.json
Labels: fix

#423 fix: Update JDK11 to JDK17 in .github/workflows/publish-release.yml
  .github/workflows/publish-release.yml
Labels: fix

#425 chore: remove unused dependencies
  pom.xml
  src/main/java/com/lpvs/service/LPVSDetectService.java
  src/main/resources/application.properties
Labels: dependencies

#429 ci: Add CI workflow for check the build of docker container
  .github/workflows/check-docker.yml
  requirements.txt
Labels: github_actions, fix

#430 fix: remove PR if max attempt reached
  src/main/java/com/lpvs/service/LPVSQueueService.java
  src/main/resources/application.properties
  src/test/java/com/lpvs/service/LPVSQueueServiceTest.java
Labels: fix

#436 ci: fix and update actions/checkout version
  .github/workflows/build.yml
  .github/workflows/check-docker.yml
  .github/workflows/findbugs.yml
  .github/workflows/java-format-checker.yml
  .github/workflows/publish-release.yml
  .github/workflows/scorecards.yml
  .github/workflows/test-suite.yml
Labels: github_actions

#437 fix: Change table name to avoid name conflicts
  doc/quick-start-guide-and-build.md
  src/main/java/com/lpvs/entity/LPVSLicense.java
  src/main/java/com/lpvs/repository/LPVSLicenseRepository.java
  src/main/resources/database_dump.sql
Labels: fix

#438 chore: refactor and update github action workflows
  .github/workflows/build.yml
  .github/workflows/check-docker.yml
  .github/workflows/codeql.yml
  .github/workflows/findbugs.yml
  .github/workflows/java-format-checker.yml
  .github/workflows/publish-release.yml
  .github/workflows/scorecards.yml
  .github/workflows/test-suite.yml
Labels: github_actions

#439 fix: Clear the queue before adding new elements
  src/main/java/com/lpvs/LicensePreValidationSystem.java
  src/main/java/com/lpvs/service/LPVSQueueService.java
  src/main/java/com/lpvs/util/LPVSCommentUtil.java
  src/test/java/com/lpvs/LicensePreValidationSystemTest.java
  src/test/java/com/lpvs/service/LPVSGitHubServiceTest.java
  src/test/java/com/lpvs/util/LPVSCommentUtilTest.java
Labels: fix

#441 build: update pom.xml
  pom.xml
Labels: dependencies

#442 fix: Fix for incorrect increment of the attempts number
  src/main/java/com/lpvs/service/LPVSQueueService.java
Labels: fix

#443 refactor: rename classes and improve `application.properties`
  README.md
  pom.xml
  src/main/java/com/lpvs/LicensePreValidationService.java
  src/main/java/com/lpvs/controller/LPVSWebController.java
  src/main/java/com/lpvs/package-info.java
  src/main/resources/application-singlescan.properties
  src/main/resources/application-web.properties
  src/main/resources/application.properties
  src/test/java/com/lpvs/LicensePreValidationServiceTest.java
Labels: enhancement

#444 docs: Update properties and corresponding documentation
  doc/quick-start-guide-and-build.md
  src/main/resources/application.properties
Labels: documentation

#445 fix: Fix incorrect log message
  src/main/java/com/lpvs/service/LPVSQueueService.java
Labels: fix

#446 fix: Fix the issue with duplicated records in pull_requests table and runtime error (missing bean)
  src/main/java/com/lpvs/config/SecurityConfig.java
  src/main/java/com/lpvs/repository/LPVSPullRequestRepository.java
  src/main/java/com/lpvs/service/LPVSQueueService.java
  src/main/resources/database_dump.sql
Labels: fix
