Repository Samsung/LPVS, pull requests merged in 2024-04, with the labels that each got.

#487 feat: Add conversion of the byte range in file to file lines
  src/main/java/com/lpvs/entity/LPVSFile.java
  src/main/java/com/lpvs/service/scan/LPVSDetectService.java
  src/main/resources/database_dump.sql
  src/test/java/com/lpvs/entity/LPVSFileTest.java
  src/test/java/com/lpvs/service/LPVSGitHubServiceTest.java
  src/test/java/com/lpvs/service/LPVSLicenseServiceTest.java
  src/test/java/com/lpvs/service/LPVSQueueServiceTest.java
  src/test/java/com/lpvs/service/scan/LPVSDetectServiceTest.java
  src/test/java/com/lpvs/service/scan/scanner/LPVSScanossDetectServiceTest.java
  src/test/resources/convert1.txt
Labels: new feature

#488 fix: Resolve an issue with incorrect file separators
  src/main/java/com/lpvs/controller/GitHubController.java
  src/main/java/com/lpvs/service/scan/LPVSDetectService.java
  src/main/java/com/lpvs/service/scan/scanner/LPVSScanossDetectService.java
  src/main/java/com/lpvs/util/LPVSFileUtil.java
  src/test/java/com/lpvs/service/scan/LPVSDetectServiceTest.java
  src/test/java/com/lpvs/util/LPVSFileUtilTest.java
Labels: fix

#491 fix: Fix Svace defects and update unit tests
  pom.xml
  src/main/java/com/lpvs/entity/LPVSFile.java
  src/test/java/com/lpvs/entity/LPVSFileTest.java
Labels: fix

#490 fix: Update scanoss dependencies
  requirements.txt
Labels: fix

#494 fix: Missing link to the scan results in case of hub link present
  src/main/java/com/lpvs/service/LPVSGitHubService.java
  src/test/java/com/lpvs/service/LPVSGitHubServiceTest.java
Labels: fix

#495 chore: Fix links in the quick-start-guide-and-build.md
  doc/quick-start-guide-and-build.md
Labels: documentation

#496 chore: Change version to v1.5.0
  pom.xml
  src/main/java/com/lpvs/service/LPVSQueueService.java
Labels: release

#497 fix: Fix license search by alternative names and remove code duplicates
  src/main/java/com/lpvs/repository/LPVSLicenseRepository.java
  src/main/java/com/lpvs/service/LPVSLicenseService.java
  src/main/java/com/lpvs/util/LPVSWebhookUtil.java
  src/main/resources/database_dump.sql
  src/test/java/com/lpvs/service/LPVSLicenseServiceTest.java
  src/test/java/com/lpvs/util/LPVSWebhookUtilTest.java
Labels: fix
