Repository Samsung/LPVS, pull requests merged in 2024-01, with the labels that each got.

#371 fix: All actions required when publishing a release are combined into…
  .github/workflows/javadoc.yml
  .github/workflows/publish-docker-img.yml
  .github/workflows/publish-jar.yml
  .github/workflows/publish-release.yml
Labels: github_actions

#385 fix: Change "npm install" to "npm ci" to install fixed version packag…
  Dockerfile
Labels: fix

#384 fix: Add `throw Exception` in case of error in `LPVSWebhookUtil` class
  src/main/java/com/lpvs/service/LPVSGitHubService.java
  src/main/java/com/lpvs/service/LPVSQueueService.java
  src/main/java/com/lpvs/service/scanner/scanoss/LPVSScanossDetectService.java
  src/main/java/com/lpvs/util/LPVSWebhookUtil.java
  src/test/java/com/lpvs/service/LPVSDetectServiceTest.java
  src/test/java/com/lpvs/service/LPVSGitHubServiceTest.java
  src/test/java/com/lpvs/service/LPVSQueueServiceTest.java
  src/test/java/com/lpvs/service/scanner/scanoss/LPVSScanossDetectServiceTest.java
  src/test/java/com/lpvs/util/LPVSWebhookUtilTest.java
Labels: fix

#387 chore: delete unused table configuration
  src/main/java/com/lpvs/util/LPVSTableConfiguration.java
  src/test/java/com/lpvs/util/LPVSTableConfigurationTest.java
Labels: enhancement

#370 feat: Add API for single pull request scan
  README.md
  doc/lpvs-api.yaml
  pom.xml
  src/main/java/com/lpvs/controller/GitHubController.java
  src/main/java/com/lpvs/controller/package-info.java
  src/main/java/com/lpvs/entity/enums/LPVSPullRequestAction.java
  src/main/java/com/lpvs/service/LPVSDetectService.java
  src/main/java/com/lpvs/service/LPVSGitHubService.java
  src/main/java/com/lpvs/service/LPVSQueueService.java
  src/main/java/com/lpvs/util/LPVSFileUtil.java
  src/main/java/com/lpvs/util/LPVSWebhookUtil.java
  src/test/java/com/lpvs/controller/GitHubControllerTest.java
  src/test/java/com/lpvs/entity/enums/LPVSPullRequestActionTest.java
  src/test/java/com/lpvs/service/LPVSDetectServiceTest.java
  src/test/java/com/lpvs/service/LPVSGitHubServiceTest.java
Labels: new feature

#388 fix: Enable scanoss dependency checking during docker container build
  Dockerfile
  requirements.txt
Labels: bug, docker

#389 docs: update guide in Quick Start part of README.md file
  README.md
Labels: documentation

#395 docs: Expand the types of commit names
  .github/CONTRIBUTING.md
Labels: documentation

#390 chore: Update package version to 1.4.0
  pom.xml
Labels: release

#396 fix: Update pyopenssl version for scanoss
  requirements.txt
Labels: fix

#400 chore: Switch from Spring 2.7 to 3.2
  .github/workflows/build.yml
  .github/workflows/codeql.yml
  .github/workflows/findbugs.yml
  .github/workflows/publish-release.yml
  .github/workflows/test-suite.yml
  README.md
  pom.xml
  src/main/java/com/lpvs/config/SecurityConfig.java
  src/main/java/com/lpvs/controller/GitHubController.java
  src/main/java/com/lpvs/entity/LPVSDetectedLicense.java
  src/main/java/com/lpvs/entity/LPVSLicense.java
  src/main/java/com/lpvs/entity/LPVSLicenseConflict.java
  src/main/java/com/lpvs/entity/LPVSPullRequest.java
  src/main/java/com/lpvs/entity/LPVSQueue.java
  src/main/java/com/lpvs/entity/auth/LPVSMember.java
  src/main/java/com/lpvs/service/LPVSDetectService.java
  src/main/java/com/lpvs/service/LPVSGitHubConnectionService.java
  src/main/java/com/lpvs/service/LPVSLicenseService.java
  src/main/java/com/lpvs/service/LPVSQueueService.java
  src/test/java/com/lpvs/config/SecurityConfigTest.java
  src/test/java/com/lpvs/controller/GitHubControllerTest.java
  src/test/java/com/lpvs/service/LPVSGitHubServiceTest.java
  src/test/java/com/lpvs/service/LPVSLicenseServiceTest.java
  src/test/java/com/lpvs/util/LPVSWebhookUtilTestFuzzer.java
Labels: dependencies, github_actions

#403 fix: Update JDK11 to JDK17 in Fuzzer
  .clusterfuzzlite/build.sh
  .github/PULL_REQUEST_TEMPLATE.md
Labels: fix

#401 build: Update JDK11 to JDK17 in Dockerfile
  Dockerfile
Labels: docker

#404 fix: Remove packages vulnerabilities in frontend
  .github/SECURITY.md
  frontend/package-lock.json
  frontend/package.json
Labels: fix

#406 docs: Add guide how to use lpvs-x.y.z.jar in other project
  README.md
Labels: documentation

#407 docs: Reorganize README.md
  README.md
  doc/quick-start-guide-and-build.md
Labels: documentation
