Repository Samsung/LPVS, pull requests merged in 2025-04, with the labels that each got.

#717 build: Update python requirements.txt with Python3.13
  requirements.txt
Labels: fix, python

#718 build(deps): Fix CVE-2024-5569 vulnerability
  .github/SECURITY.md
  requirements.txt
Labels: dependencies, fix, python

#719 fix: Add missing check for payload
  src/main/java/com/lpvs/util/LPVSPayloadUtil.java
Labels: fix
